<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'angsanaupc' => array(
    'normal' => $fontDir . '/angsau_0',
    'bold' => $fontDir . '/angsau_0',
    'italic' => $fontDir . '/angsau_0',
    'bold_italic' => $fontDir . '/angsau_0',
  ),
  'tahoma' => array(
    'normal' => $fontDir . '/Tahoma',
    'bold' => $fontDir . '/Tahoma',
    'italic' => $fontDir . '/Tahoma',
    'bold_italic' => $fontDir . '/Tahoma',
  ),
  'angsau' => array(
    'bold' => $fontDir . '/angsau',
    'bold_italic' => $fontDir . '/angsau',
    'italic' => $fontDir . '/angsau',
    'normal' => $fontDir . '/angsau',
  ),
  'ProximaNova' => array(
    'bold' => $fontDir . '/ProximaNova-Bold',
    'bold_italic' => $fontDir . '/ProximaNova-Bolditalic',
    'italic' => $fontDir . '/ProximaNova-Italic',
    'normal' => $fontDir . '/ProximaNova',
  ),
  'csprakas' => array(
    'bold' => $fontDir . '/csprakasbold-webfont',
    'bold_italic' => $fontDir . '/csprakasfdbold-webfont',
    'italic' => $fontDir . '/csprakasfd-webfont',
    'normal' => $fontDir . '/csprakas-webfont',
  ),
  'font_family' => array(
    'normal' => $fontDir . '/ProximaNova-Italic',
    'bold' => $fontDir . '/ProximaNova-Italic',
    'italic' => $fontDir . '/ProximaNova-Italic',
    'bold_italic' => $fontDir . '/ProximaNova-Italic',
  ),
  'proxima nova' => array(
    'bold' => $fontDir . '/ProximaNova-Bold',
    'bold_italic' => $fontDir . '/ProximaNova-Bolditalic',
    'italic' => $fontDir . '/ProximaNova-Italic',
    'normal' => $fontDir . '/ProximaNova',
  ),
  '\'cspraka\'' => array(
    'normal' => $fontDir . '/csprakasbold-webfont',
    'bold' => $fontDir . '/csprakasbold-webfont',
    'italic' => $fontDir . '/csprakasbold-webfont',
    'bold_italic' => $fontDir . '/csprakasbold-webfont',
  )
) ?>